fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    certmaster: "https://github.com/razorsedge/puppet-certmaster.git"
  symlinks:
    func: "#{source_dir}"
